---
title: "week2"
author: "david"
date: "March 13, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(error = TRUE)
```

## No Data Values

```{r nodata values}
# download file
download.file("https://ndownloader.figshare.com/files/7275959", "/home/kushgod/earth-analytics/week2/data/temperature_example.csv")

# import data but don't specify no data values - what happens?
temp_df <- read.csv(file = "/home/kushgod/earth-analytics/week2/data/temperature_example.csv")

# import data but specify no data values - what happens?
temp_df2 <- read.csv(file = "/home/kushgod/earth-analytics/week2/data/temperature_example.csv",
                     na.strings = c("NA", " ", "-999"))
#tests
mean(temp_df$avg_temp)
mean(temp_df2$avg_temp)
mean(temp_df$avg_temp, na.rm = TRUE)
mean(temp_df2$avg_temp, na.rm = TRUE)

#more tests

heights <- c(2, 4, 4, NA, 6)
mean(heights)
max(heights)
mean(heights, na.rm = TRUE)
max(heights, na.rm = TRUE)

```

### Plot with GGPLOT

```{r plot with GGPLOT}
# load the ggplot2 library for plotting
library(ggplot2)

# download data from figshare
# note that we already downloaded the data to our laptops previously
# but in case you don't have it - re-download it by uncommenting the code below.
#download.file(url = "https://ndownloader.figshare.com/files/7010681",
#              destfile = "data/boulder-precip.csv")

# import data
boulder_precip <- read.csv(file="/home/kushgod/earth-analytics/week2/data/boulder-precip.csv")

# view first few rows of the data
head(boulder_precip)
##     X       DATE PRECIP
## 1 756 2013-08-21    0.1
## 2 757 2013-08-26    0.1
## 3 758 2013-08-27    0.1
## 4 759 2013-09-01    0.0
## 5 760 2013-09-09    0.1
## 6 761 2013-09-10    1.0

# when we download the data we create a dataframe
# view each column of the data frame using its name (or header)
boulder_precip$DATE
##  [1] "2013-08-21" "2013-08-26" "2013-08-27" "2013-09-01" "2013-09-09"
##  [6] "2013-09-10" "2013-09-11" "2013-09-12" "2013-09-13" "2013-09-15"
## [11] "2013-09-16" "2013-09-22" "2013-09-23" "2013-09-27" "2013-09-28"
## [16] "2013-10-01" "2013-10-04" "2013-10-11"

# view the precip column
boulder_precip$PRECIP
##  [1] 0.1 0.1 0.1 0.0 0.1 1.0 2.3 9.8 1.9 1.4 0.4 0.1 0.3 0.3 0.1 0.0 0.9
## [18] 0.1

# q plot stands for quick plot. Let's use it to plot our data
qplot(x=boulder_precip$DATE,
      y=boulder_precip$PRECIP)

#messing with the colors
ggplot(data = boulder_precip)
ggplot(data = boulder_precip, aes(x = DATE, y = PRECIP))

ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) + geom_point()

# Create the plot object (nothing will render on your screen)
precip_plot <-  ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP))

# Draw the plot
precip_plot + geom_point()

#color applied
ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) + geom_point(alpha=.5, color = "blue")

#range
ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) + geom_point(alpha = 0.9, aes(color=PRECIP))

#bar plot
ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) + geom_bar(stat="identity")

#the outlines is blue!
ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) + geom_bar(stat="identity", color="blue")

#add a label
ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) +
    geom_point(alpha = 0.9, aes(color=PRECIP)) +
    ggtitle("Precipitation - Boulder, Colorado 2013")

#add x and y labels
ggplot(data = boulder_precip,  aes(x = DATE, y = PRECIP)) +
    geom_point(alpha = 0.9, aes(color=PRECIP)) +
    ggtitle("Precipitation - Boulder, Colorado 2013") +
    xlab("x label here") + ylab("y label here")
```

### Change the dates

```{r change the dates}
# convert date column to date class
boulder_precip$DATE <- as.Date(boulder_precip$DATE,
                        format="%Y-%m-%d")

# view R class of data
class(boulder_precip$DATE)
## [1] "Date"

# view results
head(boulder_precip$DATE)
## [1] "2013-08-21" "2013-08-26" "2013-08-27" "2013-09-01" "2013-09-09"
## [6] "2013-09-10"

ggplot(data=boulder_precip, aes(x=DATE, y=PRECIP)) +
      geom_bar(stat="identity") +
      ggtitle("Precipitation")
```

### USGS Stream Gage Data

```{r USGS Stream Gage Data}
# set your working directory to the earth-analytics directory
setwd("/home/kushgod/earth-analytics")

# load packages
library(ggplot2) # create efficient, professional plots
library(dplyr) # data manipulation

# set strings as factors to false
options(stringsAsFactors = FALSE)

#read data
discharge <- read.csv("/home/kushgod/earth-analytics/week2/data/discharge/06730200-discharge-daily-1986-2013.csv")

# view first 6 lines of data
head(discharge)

# Draw the plot
dis_plot + geom_point()

#range
ggplot(data = discharge,  aes(x = datetime, y = disValue)) + geom_point(alpha = 0.9, aes(color=disValue))

discharge$datetime <- as.Date(discharge$datetime, "%m/%d/%y")

discharge_sub <- discharge %>%
                        filter(datetime >= as.Date('2013-08-15') & datetime <= as.Date('2013-10-15'))

#add x and y labels
ggplot(data = discharge_sub,  aes(x = datetime, y = disValue)) +
    geom_point(alpha = 0.9, aes(color=disValue)) +
    ggtitle("USGS Stream Discharge Data") +
    xlab("Date") + ylab("Cubic feet per second")


```